export {default as Header} from './header/header'
export {default as Nav} from './nav/nav'
export {default as First} from './first/first'
export {default as Second} from './second/second'
export {default as Footer} from './footer/footer'